### PR TITLE
upgraded router

### PR DESCRIPTION
**Pull request by krawaller**
This PR upgrades react-router (and therefore also React), which fixes [this issue](https://github.com/rackt/react-router/issues/504)

### CODE REVIEW

**Comment by OAGr** [comment]
I just spend a few hours not realizing there was a dependency issue.  Started fixing it myself, then saw this.  Please accept this!  Also, good job krawaller.

**Comment by spoike** [comment]
Is this PR still relevant after the merge of #17 ?

**Comment by OAGr** [comment]
I would believe so.  It looks like that one didn't change react-router.

**Comment by spoike** [comment]
Unless @krawaller is willing to update his PR, I can take a gander at it when I have the time.

**Comment by krawaller** [comment]
I'll take a look tonight!

**Comment by krawaller** [comment]
fixed now, i think!

**Comment by eddyystop** [comment]
+1 this pull. I don't think the repo as is can be used in learning today's React+Reflux since the React-Router is so out-of-date.

**Pull request merged**
